//#ifndef TRADESTATISTICS_H
//#define TRADESTATISTICS_H
//
//#include "Huobi/Decimal.h"
//
//namespace Huobi {
//
//    /**
//     * The summary of trading in the market for the last 24 hours.
//     */
//    struct TradeStatistics {
//        /**
//         * The UNIX formatted timestamp generated by server in UTC.
//         */
//        long timestamp;
//
//        /**
//         * The opening price of last 24 hours.
//         */
//        Decimal open;
//
//        /**
//         * The last price of last 24 hours.
//         */
//        Decimal close;
//
//        /**
//         * The aggregated trading volume in USDT.
//         */
//        Decimal amount;
//
//        /**
//         * The high price of last 24 hours.
//         */
//        Decimal high;
//
//        /**
//         * The low price of last 24 hours.
//         */
//        Decimal low;
//
//        /**
//         * The number of completed trades.
//         */
//        long count;
//
//        /**
//         * The trading volume in base currency of last 24 hours.
//         */
//        Decimal volume;
//
//        static RestApiJsonParser<TradeStatistics > getTickParser() {
//            RestApiJsonParser<TradeStatistics> res;
//            res.parseJson = [](JsonWrapper json) {
//                TradeStatistics tradeStatistics = parse(json);
//                return tradeStatistics;
//            };
//            return res;
//        }
//
//        static TradeStatistics parse(JsonWrapper json) {
//            TradeStatistics tradeStatistics;
//            tradeStatistics.timestamp =
//                    TimeService::convertCSTInMillisecondToUTC(json.getLong("ts"));
//            JsonWrapper tick = json.getJsonObjectOrArray("tick");
//            tradeStatistics.amount = tick.getDecimal("amount");
//            tradeStatistics.open = tick.getDecimal("open");
//            tradeStatistics.close = tick.getDecimal("close");
//            tradeStatistics.high = tick.getDecimal("high");
//            tradeStatistics.low = tick.getDecimal("low");
//            tradeStatistics.count = tick.getLong("count");
//            tradeStatistics.volume = tick.getDecimal("vol");
//            return tradeStatistics;
//        }
//    };
//}
//
//
//#endif /* TRADESTATISTICS_H */
//
